#!/bin/sh

usage()
{
   echo "Usage $0 OPTIONS <secret_code>"
   echo "       OPTIONS:"
   echo "            -d    Force device"
   echo "            -e    Force emulator"
   echo "            -h    Prints this menu"
   exit $1
}

SECRET_CODE_ACTION=android.provider.Telephony.SECRET_CODE
SECRET_CODE_SCHEME=android_secret_code
emulator=0
device=0
secretcode=""

#Process the arguments
while getopts hde opt
do
   case "$opt" in
      d) device=1;;
      e) emulator=1;;
      h) usage 0;;
      \?) usage 0;;
   esac
done

secretcode=${@:$OPTIND:1}

if [ -z $secretcode ] ; then
    echo "[ERROR] You must supply a secret code."
    usage -1
fi

if [ $device -eq 1 -a $emulator -eq 1 ]; then
   echo "[ERROR] You can only use \"-d\" OR \"-e\""
   usage -2
fi

adb="adb"
[[ $device -eq 1 ]] && adb="adb -d"
[[ $emulator -eq 1 ]] && adb="adb -e"

echo "Sending secret code \"${secretcode}\"..."
$adb shell "am broadcast -a ${SECRET_CODE_ACTION} -d ${SECRET_CODE_SCHEME}://${secretcode}"
